
#----------------------------------------------------------
spring.application.name=authentication-service
server.port=5006

# --- Database ---
# Note: For local execution, use localhost:5433 (mapped port). For Docker, use postgres:5432.
spring.datasource.url=jdbc:postgresql://localhost:5433/auth_db
spring.datasource.username=${Username}
spring.datasource.password=${PASSOWRD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.consumer.group-id=auth-service-group
spring.kafka.consumer.auto-offset-reset=earliest

# Use ByteArray serializer/deserializer (Manual Protobuf)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer

# JWT PROVIDER
security.jwt.secretkey=ghdfg5tyvst5tui5tyer e eyyt85y  tt8yh8utr
security.jwt.expiration=3660000
jwt.private-key-path=classpath:keys/private_key.pem

# Google OAuth2 config (QMEETX)
spring.security.oauth2.client.registration.google.client-id=${ID}
spring.security.oauth2.client.registration.google.client-secret=${SECRET}
spring.security.oauth2.client.registration.google.scope=openid,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:5000/api/auth/oauth
spring.security.oauth2.client.registration.google.client-name=Google

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://openidconnect.googleapis.com/v1/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub
